### ISSUE TITLE
Changing mesos attributes procedure tells half the story

### ISSUE THREAD

**Issue by smartbit** [portworx/px-docs#309]
https://github.com/portworx/px-docs/blob/gh-pages/scheduler/mesosphere-dcos/constraints.md#add-constraints-on-slave-nodes states

> For each Mesosphere Agent node or Mesos-slave that is participating in the PX cluster, specify Mesos attributes that allow for affinity of tasks to nodes that are part of the Portworx cluster.
> If using Mesosphere/DCOS:

```
# echo MESOS_ATTRIBUTES=pxfabric:pxclust1 >> /var/lib/dcos/mesos-slave-common
# rm -f /var/lib/mesos/slave/meta/slaves/latest
# systemctl restart dcos-mesos-slave.service
# systemctl status dcos-mesos-slave.service -l
```

https://docs.mesosphere.com/1.11/administering-clusters/update-a-node/ states:

> When you change Mesos attributes (⁠⁠⁠⁠/var/lib/dcos/mesos-slave-common⁠⁠⁠⁠) or resources (⁠⁠⁠⁠/var/lib/dcos/mesos-resources⁠⁠⁠⁠), you must remove the agent node and re-register it with the master node under a new UUID. The master will then recognize the new attributes and resources specification.

Can you adapt the documentation and explain that changing the `MESOS_ATTRIBUTES` will cause that the node registers under a new UUID?

**Comment by jsilberm** [comment]
Fixed and Closed.   Thanks Bart.
