### ISSUE TITLE
404: cloud/aws-ec2-asg.html

### ISSUE THREAD

**Issue by binocarlos** [portworx/px-docs#53]
I googled:

> configure portworx with Auto Scaling Groups

and the first result was:

[Portworx AWS Auto Scaling | Portworx Documentation](https://docs.portworx.com/cloud/aws-ec2-asg.html)

which does a 404 - the actual page is [here](https://docs.portworx.com/cloud/aws/asg.html)

@msh100 @ferrantim are we able to do 302's on old urls?

**Comment by ferrantim** [comment]
Yeah you can add a "redirect_from" to the page like below
---
layout: page
title: "Cassandra and Docker Deployments: A production Ops Guide"
keywords: portworx, px-developer, cassandra, database, cluster, storage
sidebar: home_sidebar
redirect_from: "/cassandra.html"
---

can you add 

redirect_from: "/cloud/aws-ec2-asg.html" to the actual page?  That should do it.

**Comment by ferrantim** [comment]
@binocarlos
