### ISSUE TITLE
Kubernetes manifest generator env variables not working

### ISSUE THREAD

**Issue by binocarlos** [portworx/px-docs#93]
From the [Kubernetes installation](https://github.com/portworx/px-docs/blob/gh-pages/scheduler/kubernetes/install.md#install) instructions - you are given a url that (very usefully) generates the k8s manifests to run px as a daemonset.

When installing k8s using [kops](https://github.com/kubernetes/kops) - the underlying node pool is managed by an Auto Scaling Group.

Therefore - I needed to pass the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` env variables to the Portworx container (so it can manage the underlying EBS pool).

So - I crafted the following URL based on the instructions to use the `env` query parameter:

`http://install.portworx.com?cluster=mycluster&kvdb=etcd://127.0.0.1:30150&env=AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID},AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}`

This creates the following arguments in the k8s manifest:

```yaml
          - name: portworx
          image: portworx/px-enterprise:1.2.5
          terminationMessagePath: "/tmp/px-termination-log"
          imagePullPolicy: Always
          args:
             ["-k etcd://127.0.0.1:30150",
              "-c k8scluster",
              "",
              "",
              "",
              "",
              "",
              "-e AWS_ACCESS_KEY_ID=.... -e AWS_SECRET_ACCESS_KEY=...",
              "",
              "",
              "",
              "-x", "kubernetes",
              ""]
```

Which looks legit in that the values are being passed through to the manifest and then onto the Portworx process via CLI arguments.

Problem - when running the Portworx container this way - it complains that it does not have the correct permissions to use the AWS api.

When I change the manifest to the following (using the official environment variable syntax for a k8s pod) - it works fine:

```yaml
          - name: portworx
          image: portworx/px-enterprise:1.2.5
          terminationMessagePath: "/tmp/px-termination-log"
          imagePullPolicy: Always
          args:
             ["-k etcd://127.0.0.1:30150",
              "-c k8scluster",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "-x", "kubernetes",
              ""]
           env:
            - name: AWS_ACCESS_KEY_ID
              value: ${AWS_ACCESS_KEY_ID}
            - name: AWS_SECRET_ACCESS_KEY
              value: ${AWS_SECRET_ACCESS_KEY}
```

So the problem is either:

 * Portworx is not interpreting these CLI variables correctly OR
 * the automatic manifest generation script should use `env` for those variables

@harsh-px do you know where the code for `http://install.portworx.com` is living?

**Comment by harsh-px** [comment]
@binocarlos Thank you for raising the issue.

This has been fixed now. Please test it and feel free to reopen the issue if you still face the same issue.
The code for http://install.portworx.com resides in a private Portworx repository.
